##### Create matrix with all zeros (one row)
##### Create matrix with all zeros (multiple rows - with 3 rows in 5 columns)
##### Type of all zeros matrix (default is float/decimal)
##### Conevert all zeros matrix to integer (default is float/decimal)
##### Conevert all zeros matrix to boolean (default is float/decimal)
##### Create empty matrix

## Create matrix with all zeros (one row)

In [3]:
import numpy as np
arr1=np.array([0,0,0,0])
arr1

array([0, 0, 0, 0])

In [4]:
arr2=np.zeros((4))
arr2

array([0., 0., 0., 0.])

## Create matrix with all zeros (multiple rows - with 3 rows in 5 columns)

In [5]:
arr3=np.zeros((3,5))
arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Type of all zeros matrix (default is float/decimal)

In [6]:
arr3.dtype

dtype('float64')

## Conevert all zeros matrix to integer (default is float/decimal)

In [8]:
arr4=np.zeros((3,5),dtype='int32')
arr4

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## Conevert all zeros matrix to boolean (default is float/decimal)

In [9]:
arr5=np.zeros((3,5),dtype='bool')
arr5

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

## Create empty matrix

In [18]:
arr6=np.empty((6,3))
arr6

array([[4.67296746e-307, 1.69121096e-306, 1.06811354e-306],
       [9.34599605e-307, 1.11256817e-306, 1.06811422e-306],
       [1.42417221e-306, 1.11260619e-306, 8.90094053e-307],
       [1.86919378e-306, 1.06809792e-306, 1.37962456e-306],
       [1.69111861e-306, 1.78020169e-306, 1.37961777e-306],
       [7.56599807e-307, 7.56599806e-307, 1.31563739e-312]])

In [19]:
arr6.size

18