### 1. arange() - np.arange(start,end,steps)
### 2. Create 0ne-D array with np.arange
### 3. Create array with even numbers with np.arange
### 4. linespace() - values between range
### 5. reshape() - convert one-D to two-D,convert one-D to three-D  
### 6. ravel() - convert multi dimention array to one-D
### 7. flatten() - convert multi dimention array to one-D
### 8. transpose() - convert rows to columns

## 1. arange() - np.arange(start,end,steps)

In [4]:
import numpy as np
arr1=np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 2. Create 0ne-D array with np.arange

In [5]:
arr2=np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 3. Create array with even numbers with np.arange

In [12]:
arr3=np.arange(0,11,2)
arr3

array([ 0,  2,  4,  6,  8, 10])

In [14]:
# Odd Numbers
arr3=np.arange(1,11,2)
arr3

array([1, 3, 5, 7, 9])

In [17]:
# with 5 series
arr3=np.arange(5,101,5)
arr3

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

## 4. linespace() - values between range

In [21]:
# Default
arr4=np.linspace(1,2)
arr4

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [22]:
# Create with 10 values between 2-8
arr4=np.linspace(2,8,10)
arr4

array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        , 6.66666667, 7.33333333, 8.        ])

## 5. reshape() - convert one-D to two-D,convert one-D to three-D  

In [37]:
arr5=np.arange(1,16)
print(arr5)
print("\n\n3 Rows and 5 Columns\n",arr5.reshape(3,5))
print("\n\n5 Rows and 3 Columns\n",arr5.reshape(5,3))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


3 Rows and 5 Columns
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


5 Rows and 3 Columns
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


## 6. ravel() - convert multi dimention array to one-D

In [40]:
arr6=np.arange(1,13)
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
arr7=arr6.reshape(3,4)
arr7

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
arr7.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## 7. flatten() - convert multi dimention array to one-D

In [43]:
arr7.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## 8. transpose() - convert rows to columns

In [49]:
print("Actual Rows and Column values\n", arr7)
print("\n\nAfter conerting roes to columns\n",arr7.transpose())

Actual Rows and Column values
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


After conerting roes to columns
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [51]:
arr7.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])