### 1. Create two two-D arrays
### 2. Addition
### 3. Subtraction
### 4. Divide
### 5. Multiplication
### 6. Dot
### 7. Maximum value of array
### 8. Index of Maximum value of array
### 9. Maximum value of array in row
### 10. Maximum value of array in column
### 11. Minimum value of array
### 12. Minimum value of array in row
### 13. Minimum value of array in column
### 14. Index of Minimum value of array
### 15. Sum of all elements in array
### 16. Sum of all elements in array - only columns
### 17. Sum of all elements in array - only Rows
### 18. Average of all elements in array
### 19. Square root of each elements in array
### 20. Standard division of all elements in array
### 21. Exponent of each elements in array
### 22. Log of each elements in array
### 23. Log of each elements in array

## 1. Create two two-D arrays

In [13]:
import numpy as np
arr1=np.arange(1,13).reshape(3,4)
arr2=np.arange(1,13).reshape(3,4)
print(arr1)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Addition

In [14]:
arr1+arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [15]:
np.add(arr1,arr2)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

## 3. Subtraction

In [16]:
arr1-arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
np.subtract(arr1,arr2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## 4. Divide

In [19]:
arr1/arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.divide(arr1,arr2)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## 5. Multiplication

In [21]:
arr1*arr2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [22]:
np.multiply(arr1,arr2)

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

## 6. Dot

In [27]:
arr1=np.arange(1,17).reshape(4,4)
arr2=np.arange(1,17).reshape(4,4)
print(arr1)
print(arr2)
arr1.dot(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[ 90, 100, 110, 120],
       [202, 228, 254, 280],
       [314, 356, 398, 440],
       [426, 484, 542, 600]])

In [28]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)
# [[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]

array([[37, 40],
       [85, 92]])

In [31]:
a @ b

array([[37, 40],
       [85, 92]])

## 7. Maximum value of array

In [30]:
print(arr1)
np.max(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


16

## 8. Index of Maximum value of array - position of maximum value

In [32]:
np.argmax(arr1)

15

## 9. Maximum value of array in row

In [38]:
print(arr1)
np.max(arr1,axis=1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([ 4,  8, 12, 16])

## 10. Maximum value of array in column

In [35]:
print(arr1)
np.max(arr1,axis=0)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([13, 14, 15, 16])

## 11. Minimum value of array

In [40]:
print(arr1)
np.min(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


1

## 12. Minimum value of array in row

In [42]:
np.min(arr1,axis=0)

array([1, 2, 3, 4])

## 13. Minimum value of array in column

In [44]:
np.min(arr1,axis=1)

array([ 1,  5,  9, 13])

## 14. Index of Minimum value of array

In [45]:
np.argmin(arr1)

0

## 15. Sum of all elements in array

In [47]:
np.sum(arr1)

136

## 16. Sum of all elements in array - only columns

print(arr1)
np.sum(arr1,axis=0)

## 17. Sum of all elements in array - only Rows

In [52]:
print(arr1)
np.sum(arr1,axis=1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([10, 26, 42, 58])

## 18. Average of all elements in array

In [53]:
print(arr1)
np.mean(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


8.5

## 19. Square root of each elements in array

In [54]:
print(arr1)
np.sqrt(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335, 4.        ]])

## 20. Standard division of all elements in array

In [55]:
print(arr1)
np.std(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


4.6097722286464435

## 21. Exponent of each elements in array

In [56]:
print(arr1)
np.exp(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05],
       [4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06]])

## 22. Log of each elements in array

In [57]:
print(arr1)
np.log(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665],
       [2.56494936, 2.63905733, 2.7080502 , 2.77258872]])

## 23. Log of each elements in array

In [58]:
print(arr1)
np.log10(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804, 0.90308999],
       [0.95424251, 1.        , 1.04139269, 1.07918125],
       [1.11394335, 1.14612804, 1.17609126, 1.20411998]])